name: "Dubbo Lane Test"
description: "Auto test for dubbo lane"
runs:
  using: "composite"
  steps:
    - name: entry
      uses: ./.github/actions/common/entry
      with:
        log-dir: ./logs/dubbo-lane
    - name: package dubbo 2.5.x tests
      shell: bash
      if: matrix.dubbo-version == '2-5'
      run: mvn package -Dalibaba.dubbo.version=2.5.${{ matrix.dubbo-versions }} -DskipTests -P260 --file sermant-integration-tests/dubbo-test/pom.xml
    - name: package dubbo 2.6.0 tests
      shell: bash
      if: matrix.dubbo-version == '2-6' && matrix.dubbo-versions == '0'
      run: mvn package -Dalibaba.dubbo.version=2.6.${{ matrix.dubbo-versions }} -DskipTests -P260 --file sermant-integration-tests/dubbo-test/pom.xml
    - name: package dubbo 2.6.x tests
      shell: bash
      if: matrix.dubbo-version == '2-6' && matrix.dubbo-versions != '0'
      run: mvn package -Dalibaba.dubbo.version=2.6.${{ matrix.dubbo-versions }} -DskipTests --file sermant-integration-tests/dubbo-test/pom.xml
    - name: package dubbo 2.7.x tests
      shell: bash
      if: matrix.dubbo-version == '2-7'
      run: mvn package -Ddubbo.version=2.7.${{ matrix.dubbo-versions }} -DskipTests --file sermant-integration-tests/dubbo-test/pom.xml
    - name: post config to local-cse
      shell: bash
      env:
        TEST_TYPE: lane-config
      run: mvn test --file sermant-integration-tests/dubbo-test/pom.xml
    - name: start provider service
      shell: bash
      env:
        servicecomb.service.enableDubboRegister: true
        servicecomb.service.enableSpringRegister: true
        dynamic.config.dynamicConfigType: KIE
        dynamic.config.serverAddress: 127.0.0.1:30110
        SERVICE_META_ENVIRONMENT: development
        SERVICE_META_APPLICATION: lane
        SERVICE_META_VERSION: 1.0.0
        SERVER_PORT: 18021
        DUBBO_PROTOCOL_PORT: 18821
      run: |
        nohup java -javaagent:sermant-agent-${{ env.sermantVersion }}/agent/sermant-agent.jar=appName=dubbo-integration-provider -jar \
        sermant-integration-tests/dubbo-test/dubbo-${{ env.projectPath }}-integration-provider/target/dubbo-integration-provider.jar > ${{ env.logDir }}/dubbo-provider.log 2>&1 &
    - name: start second provider service
      shell: bash
      env:
        servicecomb.service.enableDubboRegister: true
        servicecomb.service.enableSpringRegister: true
        dynamic.config.dynamicConfigType: KIE
        dynamic.config.serverAddress: 127.0.0.1:30110
        SERVICE_META_ENVIRONMENT: development
        SERVICE_META_APPLICATION: lane
        SERVICE_META_VERSION: 1.0.1
        SERVER_PORT: 18022
        DUBBO_PROTOCOL_PORT: 18822
      run: |
        nohup java -javaagent:sermant-agent-${{ env.sermantVersion }}/agent/sermant-agent.jar=appName=dubbo-integration-provider -jar \
        sermant-integration-tests/dubbo-test/dubbo-${{ env.projectPath }}-integration-provider/target/dubbo-integration-provider.jar > ${{ env.logDir }}/dubbo-provider2.log 2>&1 &
    - name: waiting for providers start
      shell: bash
      run: |
        bash ./sermant-integration-tests/scripts/checkService.sh http://127.0.0.1:18021/actuator/health 120
        bash ./sermant-integration-tests/scripts/checkService.sh http://127.0.0.1:18022/actuator/health 120
    - name: start consumer service
      shell: bash
      env:
        servicecomb.service.enableDubboRegister: true
        servicecomb.service.enableSpringRegister: true
        dynamic.config.dynamicConfigType: KIE
        dynamic.config.serverAddress: 127.0.0.1:30110
        SERVICE_META_ENVIRONMENT: development
        SERVICE_META_APPLICATION: lane
        SERVICE_META_VERSION: 1.0.0
        SERVER_PORT: 18023
        DUBBO_PROTOCOL_PORT: 18823
      run: |
        nohup java -javaagent:sermant-agent-${{ env.sermantVersion }}/agent/sermant-agent.jar=appName=dubbo-integration-consumer -jar \
        sermant-integration-tests/dubbo-test/dubbo-${{ env.projectPath }}-integration-consumer/target/dubbo-integration-consumer.jar > ${{ env.logDir }}/dubbo-consumer.log 2>&1 &
    - name: start second consumer service
      shell: bash
      env:
        servicecomb.service.enableDubboRegister: true
        servicecomb.service.enableSpringRegister: true
        dynamic.config.dynamicConfigType: KIE
        dynamic.config.serverAddress: 127.0.0.1:30110
        SERVICE_META_ENVIRONMENT: development
        SERVICE_META_APPLICATION: lane
        SERVICE_META_VERSION: 1.0.1
        SERVER_PORT: 18024
        DUBBO_PROTOCOL_PORT: 18824
      run: |
        nohup java -javaagent:sermant-agent-${{ env.sermantVersion }}/agent/sermant-agent.jar=appName=dubbo-integration-consumer -jar \
        sermant-integration-tests/dubbo-test/dubbo-${{ env.projectPath }}-integration-consumer/target/dubbo-integration-consumer.jar > ${{ env.logDir }}/dubbo-consumer2.log 2>&1 &
    - name: waiting for consumer start
      shell: bash
      run: |
        bash ./sermant-integration-tests/scripts/checkService.sh http://127.0.0.1:18023/actuator/health 120
        bash ./sermant-integration-tests/scripts/checkService.sh http://127.0.0.1:18024/actuator/health 120
    - name: start controller service
      shell: bash
      env:
        servicecomb.service.enableDubboRegister: true
        servicecomb.service.enableSpringRegister: true
        dynamic.config.dynamicConfigType: KIE
        dynamic.config.serverAddress: 127.0.0.1:30110
        SERVICE_META_ENVIRONMENT: development
        SERVICE_META_APPLICATION: lane
        SERVER_PORT: 18020
      run: |
        nohup java -javaagent:sermant-agent-${{ env.sermantVersion }}/agent/sermant-agent.jar=appName=dubbo-integration-controller -jar \
        sermant-integration-tests/dubbo-test/dubbo-${{ env.projectPath }}-integration-controller/target/dubbo-integration-controller.jar > ${{ env.logDir }}/dubbo-controller.log 2>&1 &
    - name: waiting for controller start
      shell: bash
      run: |
        bash ./sermant-integration-tests/scripts/checkService.sh http://127.0.0.1:18020/actuator/health 120
    - name: integration test
      shell: bash
      env:
        TEST_TYPE: lane
      run: mvn -Dcontroller.port=18020 test --file sermant-integration-tests/dubbo-test/pom.xml
    - name: exit
      if: always()
      uses: ./.github/actions/common/exit
      with:
        processor-keyword: dubbo
    - name: if failure then upload error log
      uses: actions/upload-artifact@v3
      if: ${{ failure() || cancelled() }}
      with:
        name: (test-for-dubbo-lane)-(${{ matrix.dubbo-version }}-${{ matrix.dubbo-versions }})-logs
        path: |
          ./*.log
          ./logs/**/*.log
        if-no-files-found: warn
        retention-days: 2
