name: "xDS Service Discovery Test"
description: "Auto test for xds service discovery"
runs:
  using: composite
  steps:
    - name: prepare image
      shell: bash
      run: |
        cp -r sermant-integration-tests/xds-service-test/product/sermant-agent-*/agent sermant-integration-tests/xds-service-test/product/spring-client/
        cp -r sermant-integration-tests/xds-service-test/product/sermant-agent-*/agent sermant-integration-tests/xds-service-test/product/spring-server/
        mvn package -DskipTests -pl spring-common,spring-client,spring-server -Pxds-discovery --file \
        sermant-integration-tests/xds-service-test/pom.xml
    - name: build docker image
      shell: bash
      run: |
        cd sermant-integration-tests/xds-service-test/product/spring-server/
        minikube image build -t spring-server:1.0.0 .
        cd ../spring-client/
        minikube image build -t spring-client:1.0.0 .
        eval $(minikube docker-env)
        docker images
    - name: start spring-client and spring-server
      shell: bash
      run: |
        kubectl apply -f sermant-integration-tests/xds-service-test/script/discovery/spring-client-sermant-xds-open.yaml
        kubectl apply -f sermant-integration-tests/xds-service-test/script/discovery/spring-server.yaml
    - name: Wait for spring-client pod and spring-server pod to be ready
      shell: bash
      run: |
        kubectl wait --for=condition=ready pod -l app=spring-client --timeout=10s
        kubectl wait --for=condition=ready pod -l app=spring-server --timeout=10s
        sleep 10s
        nohup kubectl port-forward svc/spring-client 8080:8080 &
        sleep 2s
        bash ./sermant-integration-tests/scripts/checkService.sh http://127.0.0.1:8080/checkStatus 150
        nohup kubectl port-forward svc/spring-server 8081:8081 &
        sleep 2s
        bash ./sermant-integration-tests/scripts/checkService.sh http://127.0.0.1:8081/hello 150
        pkill -f "kubectl port-forward svc/spring-server"
    - name: test one server
      shell: bash
      run: |
        mvn test -Dxds.service.integration.test.type=DISCOVERY_ONE_SERVER_INSTANCE --file \
        sermant-integration-tests/xds-service-test/xds-service-integration-test/pom.xml
    - name: stop spring-server
      shell: bash
      run: |
        kubectl delete -f sermant-integration-tests/xds-service-test/script/discovery/spring-server.yaml
        sleep 10s
    - name: test the number of spring-server instances changes from 1 to 0
      shell: bash
      run: |
        mvn test -Dxds.service.integration.test.type=DISCOVERY_ZERO_SERVER_INSTANCE --file \
        sermant-integration-tests/xds-service-test/xds-service-integration-test/pom.xml
    - name: start spring-server with 2 replicas
      shell: bash
      run: |
        kubectl apply -f sermant-integration-tests/xds-service-test/script/discovery/spring-server-2-replicas.yaml
        kubectl wait --for=condition=ready pod -l app=spring-server --timeout=10s
        sleep 10s
        nohup kubectl port-forward svc/spring-server 8081:8081 &
        sleep 2s
        bash ./sermant-integration-tests/scripts/checkService.sh http://127.0.0.1:8081/hello 150
        pkill -f "kubectl port-forward svc/spring-server"
    - name: test the number of spring-server instances changes from 0 to 2
      shell: bash
      run: |
        mvn test -Dxds.service.integration.test.type=DISCOVERY_TWO_SERVER_INSTANCE --file \
        sermant-integration-tests/xds-service-test/xds-service-integration-test/pom.xml
    - name: create istio token
      shell: bash
      run: |
        kubectl create serviceaccount istio-test
        TOKEN=$(kubectl create token istio-test --duration=1h --audience=istio-ca)
        kubectl create secret generic istio-test-secret \
          --from-literal=token=${TOKEN} \
          --type="istio.io/key-and-cert" \
          -n default
    - name: restart spring-client and sermant xds service use security mode
      shell: bash
      run: |
        kubectl delete -f sermant-integration-tests/xds-service-test/script/discovery/spring-client-sermant-xds-open.yaml
        sleep 10s
        kubectl apply -f sermant-integration-tests/xds-service-test/script/discovery/spring-client-sermant-xds-subscribe-secure.yaml
        kubectl wait --for=condition=ready pod -l app=spring-client --timeout=10s
        sleep 10s
        pkill -f "kubectl port-forward svc/spring-client"
        nohup kubectl port-forward svc/spring-client 8080:8080 &
        sleep 2s
        bash ./sermant-integration-tests/scripts/checkService.sh http://127.0.0.1:8080/checkStatus 150
    - name: test sermant xds service use security mode
      shell: bash
      run: |
        mvn test -Dxds.service.integration.test.type=SECRET --file \
        sermant-integration-tests/xds-service-test/xds-service-integration-test/pom.xml
    - name: test subscribe to get service instance
      shell: bash
      run: |
        mvn test -Dxds.service.integration.test.type=DISCOVERY_SUBSCRIBE --file \
        sermant-integration-tests/xds-service-test/xds-service-integration-test/pom.xml
    - name: close all service
      shell: bash
      run: |
        kubectl delete -f sermant-integration-tests/xds-service-test/script/discovery/spring-client-sermant-xds-subscribe-secure.yaml
        kubectl delete -f sermant-integration-tests/xds-service-test/script/discovery/spring-server-2-replicas.yaml
