/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 */

package com.huawei.emergency.mapper;

import com.huawei.emergency.entity.EmergencyScript;
import com.huawei.emergency.entity.EmergencyScriptExample;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.List;

/**
 * 脚本mapper
 *
 * @author h30009881
 * @since 2021-11-15
 **/
@Mapper
public interface EmergencyScriptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emergency_script
     *
     * @mbg.generated
     */
    long countByExample(EmergencyScriptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emergency_script
     *
     * @mbg.generated
     */
    int deleteByExample(EmergencyScriptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emergency_script
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer scriptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emergency_script
     *
     * @mbg.generated
     */
    int insert(EmergencyScript record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emergency_script
     *
     * @mbg.generated
     */
    int insertSelective(EmergencyScript record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emergency_script
     *
     * @mbg.generated
     */
    List<EmergencyScript> selectByExampleWithBLOBs(EmergencyScriptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emergency_script
     *
     * @mbg.generated
     */
    List<EmergencyScript> selectByExample(EmergencyScriptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emergency_script
     *
     * @mbg.generated
     */
    EmergencyScript selectByPrimaryKey(Integer scriptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emergency_script
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EmergencyScript record, @Param("example") EmergencyScriptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emergency_script
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") EmergencyScript record, @Param("example") EmergencyScriptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emergency_script
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EmergencyScript record, @Param("example") EmergencyScriptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emergency_script
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EmergencyScript record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emergency_script
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(EmergencyScript record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emergency_script
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EmergencyScript record);


    List<EmergencyScript> listScript(String userName,String auth, String scriptName, String scriptUser,String status);

    EmergencyScript getScriptInfo(int scriptId);

    @Select("select script_name from emergency_script where script_id = #{scriptId}")
    String selectScriptNameById(int scriptId);

    List<String> searchScript(String scriptName, String userName,String auth,String status);

    EmergencyScript getScriptByName(String scriptName);

    String selectUserById(int scriptId);
}