name: "Spring Lane Test"
description: "Auto test for spring Lane"
runs:
  using: "composite"
  steps:
    - name: entry
      uses: ./.github/actions/common/entry
      with:
        log-dir: ./logs/lane
    - name: 1.5.x config
      if: matrix.springBootVersion == '1.5.0.RELEASE' && matrix.springCloudVersion == 'Edgware.SR2'
      shell: bash
      run: |
        echo "tailVersion=-1.5.x" >> $GITHUB_ENV
        echo "healthApi=health" >> $GITHUB_ENV
    - name: 2.x config
      if: matrix.springBootVersion != '1.5.0.RELEASE'
      shell: bash
      run: |
        echo "healthApi=actuator/health" >> $GITHUB_ENV
    - name: package common demos
      shell: bash
      run: |
        sed -i 's|<version>${{ env.projectSpringBootVersion }}</version>|<version>${{ matrix.springBootVersion }}</version>|g' sermant-integration-tests/spring-test/pom.xml
        mvn package -Dspring.cloud.version=${{ matrix.springCloudVersion }} -Dhttp.client.version=${{ matrix.httpClientVersion }} -Dspring.boot.version=${{ matrix.springBootVersion }} -DskipTests -P common-test${{ env.tailVersion }} --file sermant-integration-tests/spring-test/pom.xml
    - name: package zuul demo
      shell: bash
      if: matrix.springCloudVersion == 'Edgware.SR2' || matrix.springCloudVersion == 'Finchley.RELEASE' || matrix.springCloudVersion == 'Greenwich.RELEASE' || matrix.springCloudVersion == 'Hoxton.RELEASE'
      run: |
        sed -i 's|<version>${{ env.projectSpringBootVersion }}</version>|<version>${{ matrix.springBootVersion }}</version>|g' sermant-integration-tests/spring-test/pom.xml
        mvn package -Dspring.cloud.version=${{ matrix.springCloudVersion }} -Dhttp.client.version=${{ matrix.httpClientVersion }} -Dspring.boot.version=${{ matrix.springBootVersion }} -DskipTests -P zuul --file sermant-integration-tests/spring-test/spring-common-demos/pom.xml
    - name: package gateway demo
      shell: bash
      if: matrix.springCloudVersion != 'Edgware.SR2'
      run: |
        sed -i 's|<version>${{ env.projectSpringBootVersion }}</version>|<version>${{ matrix.springBootVersion }}</version>|g' sermant-integration-tests/spring-test/pom.xml
        mvn package -Dspring.cloud.version=${{ matrix.springCloudVersion }} -Dhttp.client.version=${{ matrix.httpClientVersion }} -Dspring.boot.version=${{ matrix.springBootVersion }} -DskipTests -P gateway --file sermant-integration-tests/spring-test/spring-common-demos/pom.xml
    - name: post config to local-cse
      shell: bash
      run: mvn test -Dsermant.integration.test.type=LANE_CONFIG --file sermant-integration-tests/spring-test/pom.xml
    - name: start feign provider service
      shell: bash
      env:
        SERVICECOMB_SERVICE_ENABLESPRINGREGISTER: true
        SERVICECOMB_SERVICE_PREFERIPADDRESS: true
        dynamic.config.dynamicConfigType: KIE
        dynamic.config.serverAddress: 127.0.0.1:30110
        SERVICE_META_ENVIRONMENT: development
        SERVICE_META_APPLICATION: lane
        SERVICE_META_VERSION: 1.0.0
        SERVER_PORT: 8002
      run: |
        nohup java -javaagent:sermant-agent-${{ env.sermantVersion }}/agent/sermant-agent.jar=appName=default -jar \
        sermant-integration-tests/spring-test/spring-common-demos/spring-common-feign${{ env.tailVersion }}/feign-provider${{ env.tailVersion }}/target/feign-provider${{ env.tailVersion }}.jar > ${{ env.logDir }}/feign-provider.log 2>&1 &
    - name: start second feign provider service
      shell: bash
      env:
        SERVICECOMB_SERVICE_ENABLESPRINGREGISTER: true
        SERVICECOMB_SERVICE_PREFERIPADDRESS: true
        dynamic.config.dynamicConfigType: KIE
        dynamic.config.serverAddress: 127.0.0.1:30110
        SERVICE_META_ENVIRONMENT: development
        SERVICE_META_APPLICATION: lane
        SERVICE_META_VERSION: 1.0.1
        SERVER_PORT: 8003
      run: |
        nohup java -javaagent:sermant-agent-${{ env.sermantVersion }}/agent/sermant-agent.jar=appName=default -jar \
        sermant-integration-tests/spring-test/spring-common-demos/spring-common-feign${{ env.tailVersion }}/feign-provider${{ env.tailVersion }}/target/feign-provider${{ env.tailVersion }}.jar > ${{ env.logDir }}/feign-provider2.log 2>&1 &
    - name: start feign consumer service
      shell: bash
      env:
        SERVICECOMB_SERVICE_ENABLESPRINGREGISTER: true
        SERVICECOMB_SERVICE_PREFERIPADDRESS: true
        dynamic.config.dynamicConfigType: KIE
        dynamic.config.serverAddress: 127.0.0.1:30110
        SERVICE_META_ENVIRONMENT: development
        SERVICE_META_APPLICATION: lane
        SERVICE_META_VERSION: 1.0.0
        SERVER_PORT: 8004
      run: |
        nohup java -javaagent:sermant-agent-${{ env.sermantVersion }}/agent/sermant-agent.jar=appName=default -jar \
        sermant-integration-tests/spring-test/spring-common-demos/spring-common-feign${{ env.tailVersion }}/feign-consumer${{ env.tailVersion }}/target/feign-consumer${{ env.tailVersion }}.jar > ${{ env.logDir }}/feign-consumer.log 2>&1 &
    - name: start second feign consumer service
      shell: bash
      env:
        SERVICECOMB_SERVICE_ENABLESPRINGREGISTER: true
        SERVICECOMB_SERVICE_PREFERIPADDRESS: true
        dynamic.config.dynamicConfigType: KIE
        dynamic.config.serverAddress: 127.0.0.1:30110
        SERVICE_META_ENVIRONMENT: development
        SERVICE_META_APPLICATION: lane
        SERVICE_META_VERSION: 1.0.1
        SERVER_PORT: 8005
      run: |
        nohup java -javaagent:sermant-agent-${{ env.sermantVersion }}/agent/sermant-agent.jar=appName=default -jar \
        sermant-integration-tests/spring-test/spring-common-demos/spring-common-feign${{ env.tailVersion }}/feign-consumer${{ env.tailVersion }}/target/feign-consumer${{ env.tailVersion }}.jar > ${{ env.logDir }}/feign-consumer2.log 2>&1 &
    - name: start resttemplate provider service
      shell: bash
      env:
        SERVICECOMB_SERVICE_ENABLESPRINGREGISTER: true
        SERVICECOMB_SERVICE_PREFERIPADDRESS: true
        dynamic.config.dynamicConfigType: KIE
        dynamic.config.serverAddress: 127.0.0.1:30110
        SERVICE_META_ENVIRONMENT: development
        SERVICE_META_APPLICATION: lane
        SERVICE_META_VERSION: 1.0.0
        SERVER_PORT: 8006
      run: |
        nohup java -javaagent:sermant-agent-${{ env.sermantVersion }}/agent/sermant-agent.jar=appName=default -jar \
        sermant-integration-tests/spring-test/spring-common-demos/spring-common-resttemplate/rest-provider/target/rest-provider.jar > ${{ env.logDir }}/rest-provider.log 2>&1 &
    - name: start second resttemplate provider service
      shell: bash
      env:
        SERVICECOMB_SERVICE_ENABLESPRINGREGISTER: true
        SERVICECOMB_SERVICE_PREFERIPADDRESS: true
        dynamic.config.dynamicConfigType: KIE
        dynamic.config.serverAddress: 127.0.0.1:30110
        SERVICE_META_ENVIRONMENT: development
        SERVICE_META_APPLICATION: lane
        SERVICE_META_VERSION: 1.0.1
        SERVER_PORT: 8007
      run: |
        nohup java -javaagent:sermant-agent-${{ env.sermantVersion }}/agent/sermant-agent.jar=appName=default -jar \
        sermant-integration-tests/spring-test/spring-common-demos/spring-common-resttemplate/rest-provider/target/rest-provider.jar > ${{ env.logDir }}/rest-provider2.log 2>&1 &
    - name: start resttemplate consumer service
      shell: bash
      env:
        SERVICECOMB_SERVICE_ENABLESPRINGREGISTER: true
        SERVICECOMB_SERVICE_PREFERIPADDRESS: true
        dynamic.config.dynamicConfigType: KIE
        dynamic.config.serverAddress: 127.0.0.1:30110
        SERVICE_META_ENVIRONMENT: development
        SERVICE_META_APPLICATION: lane
        SERVICE_META_VERSION: 1.0.0
        SERVER_PORT: 8008
      run: |
        nohup java -javaagent:sermant-agent-${{ env.sermantVersion }}/agent/sermant-agent.jar=appName=default -jar \
        sermant-integration-tests/spring-test/spring-common-demos/spring-common-resttemplate/rest-consumer/target/rest-consumer.jar > ${{ env.logDir }}/rest-consumer.log 2>&1 &
    - name: start second resttemplate consumer service
      shell: bash
      env:
        SERVICECOMB_SERVICE_ENABLESPRINGREGISTER: true
        SERVICECOMB_SERVICE_PREFERIPADDRESS: true
        dynamic.config.dynamicConfigType: KIE
        dynamic.config.serverAddress: 127.0.0.1:30110
        SERVICE_META_ENVIRONMENT: development
        SERVICE_META_APPLICATION: lane
        SERVICE_META_VERSION: 1.0.1
        SERVER_PORT: 8009
      run: |
        nohup java -javaagent:sermant-agent-${{ env.sermantVersion }}/agent/sermant-agent.jar=appName=default -jar \
        sermant-integration-tests/spring-test/spring-common-demos/spring-common-resttemplate/rest-consumer/target/rest-consumer.jar > ${{ env.logDir }}/rest-consumer2.log 2>&1 &
    - name: start gateway
      shell: bash
      if: matrix.springCloudVersion != 'Edgware.SR2'
      env:
        SERVICECOMB_SERVICE_ENABLESPRINGREGISTER: true
        SERVICECOMB_SERVICE_PREFERIPADDRESS: true
        dynamic.config.dynamicConfigType: KIE
        dynamic.config.serverAddress: 127.0.0.1:30110
        SERVICE_META_ENVIRONMENT: development
        SERVICE_META_APPLICATION: lane
        SERVER_PORT: 8001
      run: |
        nohup java -javaagent:sermant-agent-${{ env.sermantVersion }}/agent/sermant-agent.jar=appName=default -jar \
        sermant-integration-tests/spring-test/spring-common-demos/spring-common-gateway/target/spring-common-gateway.jar > ${{ env.logDir }}/spring-common-gateway.log 2>&1 &
        bash ./sermant-integration-tests/scripts/checkService.sh http://127.0.0.1:8001/actuator/health 120
    - name: start zuul
      shell: bash
      if: matrix.springCloudVersion == 'Edgware.SR2' || matrix.springCloudVersion == 'Finchley.RELEASE' || matrix.springCloudVersion == 'Greenwich.RELEASE' || matrix.springCloudVersion == 'Hoxton.RELEASE'
      env:
        SERVICECOMB_SERVICE_ENABLESPRINGREGISTER: true
        SERVICECOMB_SERVICE_PREFERIPADDRESS: true
        dynamic.config.dynamicConfigType: KIE
        dynamic.config.serverAddress: 127.0.0.1:30110
        SERVICE_META_ENVIRONMENT: development
        SERVICE_META_APPLICATION: lane
        SERVER_PORT: 8000
      run: |
        nohup java -javaagent:sermant-agent-${{ env.sermantVersion }}/agent/sermant-agent.jar=appName=default -jar \
        sermant-integration-tests/spring-test/spring-common-demos/spring-common-zuul/target/spring-common-zuul.jar > ${{ env.logDir }}/spring-common-zuul.log 2>&1 &
        bash ./sermant-integration-tests/scripts/checkService.sh http://127.0.0.1:8000/${{ env.healthApi }} 120
    - name: waiting for services start
      shell: bash
      run: |
        ps -ef | grep java
        bash ./sermant-integration-tests/scripts/checkService.sh http://127.0.0.1:8002/${{ env.healthApi }} 120
        bash ./sermant-integration-tests/scripts/checkService.sh http://127.0.0.1:8003/${{ env.healthApi }} 120
        bash ./sermant-integration-tests/scripts/checkService.sh http://127.0.0.1:8004/${{ env.healthApi }} 120
        bash ./sermant-integration-tests/scripts/checkService.sh http://127.0.0.1:8005/${{ env.healthApi }} 120
        bash ./sermant-integration-tests/scripts/checkService.sh http://127.0.0.1:8006/${{ env.healthApi }} 120
        bash ./sermant-integration-tests/scripts/checkService.sh http://127.0.0.1:8007/${{ env.healthApi }} 120
        bash ./sermant-integration-tests/scripts/checkService.sh http://127.0.0.1:8008/${{ env.healthApi }} 120
        bash ./sermant-integration-tests/scripts/checkService.sh http://127.0.0.1:8009/${{ env.healthApi }} 120
    - name: integration test module LANE
      shell: bash
      env:
        SPRING_CLOUD_VERSION: ${{ matrix.springCloudVersion }}
        SPRING_BOOT_VERSION: ${{ matrix.springBootVersion }}
      run: mvn test -Dsermant.integration.test.type=LANE --file sermant-integration-tests/spring-test/pom.xml
    - name: exit
      if: always()
      uses: ./.github/actions/common/exit
      with:
        processor-keyword: feign|rest|zuul|gateway
    - name: if failure then upload error log
      uses: actions/upload-artifact@v3
      if: ${{ failure() || cancelled() }}
      with:
        name: (${{ github.job }})-lane-(${{ matrix.springBootVersion }}-${{ matrix.springCloudVersion }})-logs
        path: |
          ./*.log
          ./logs/**
        if-no-files-found: warn
        retention-days: 2
