spring:
  application:
    name: spring-server
  cloud:
    zookeeper:
      connect-string: ${ZOOKEEPER_IP}:2181
      enabled: ${ZOOKEEPER_ENABLED:false}
server:
  port: 8081
connectTimeout: 5000
retryTimeout: 10000
statusCode: 200
