<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>io.sermant</groupId>
        <artifactId>sermant-tag-transmission</artifactId>
        <version>1.0.0</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>tag-transmission-okhttp34-plugin</artifactId>
    <name>${project.artifactId}</name>
    <description>OkHttp3.x,4.x tag transmission plugin</description>

    <properties>
        <okhttp.version>3.14.9</okhttp.version>
        <assertj.version>3.27.3</assertj.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.sermant</groupId>
            <artifactId>tag-transmission-common</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>io.sermant</groupId>
            <artifactId>sermant-agentcore-core</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
            <version>${okhttp.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>${assertj.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-inline</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
