package com.huawei.emergency.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.springframework.web.multipart.MultipartFile;

import java.sql.Timestamp;
import java.util.Date;

public class EmergencyScript {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emergency_script.script_id
     *
     * @mbg.generated
     */
    @JsonProperty("script_id")
    private Integer scriptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emergency_script.script_name
     *
     * @mbg.generated
     */
    @JsonProperty("script_name")
    private String scriptName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emergency_script.is_public
     *
     * @mbg.generated
     */
    @JsonProperty("public")
    private String isPublic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emergency_script.script_type
     *
     * @mbg.generated
     */
    @JsonProperty("language")
    private String scriptType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emergency_script.submit_info
     *
     * @mbg.generated
     */
    @JsonProperty("submit_info")
    private String submitInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emergency_script.have_password
     *
     * @mbg.generated
     */
    @JsonProperty("has_pwd")
    private String havePassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emergency_script.password_mode
     *
     * @mbg.generated
     */
    @JsonProperty("pwd_from")
    private String passwordMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emergency_script.password
     *
     * @mbg.generated
     */
    @JsonProperty("pwd")
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emergency_script.server_user
     *
     * @mbg.generated
     */
    @JsonProperty("account")
    private String serverUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emergency_script.server_ip
     *
     * @mbg.generated
     */
    private String serverIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emergency_script.script_user
     *
     * @mbg.generated
     */
    @JsonProperty("owner")
    private String scriptUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emergency_script.update_time
     *
     * @mbg.generated
     */
    @JsonProperty("create_time")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Timestamp updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emergency_script.param
     *
     * @mbg.generated
     */
    private String param;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emergency_script.script_status
     *
     * @mbg.generated
     */
    @JsonProperty("status")
    private String scriptStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emergency_script.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * 审核不通过原因
     */
    private String comment;

    @JsonProperty("status_label")
    private String statusLabel;

    public String getStatusLabel() {
        return statusLabel;
    }

    public void setStatusLabel(String statusLabel) {
        this.statusLabel = statusLabel;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emergency_script.script_id
     *
     * @return the value of emergency_script.script_id
     *
     * @mbg.generated
     */
    public Integer getScriptId() {
        return scriptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emergency_script.script_id
     *
     * @param scriptId the value for emergency_script.script_id
     *
     * @mbg.generated
     */
    public void setScriptId(Integer scriptId) {
        this.scriptId = scriptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emergency_script.script_name
     *
     * @return the value of emergency_script.script_name
     *
     * @mbg.generated
     */
    public String getScriptName() {
        return scriptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emergency_script.script_name
     *
     * @param scriptName the value for emergency_script.script_name
     *
     * @mbg.generated
     */
    public void setScriptName(String scriptName) {
        this.scriptName = scriptName == null ? null : scriptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emergency_script.is_public
     *
     * @return the value of emergency_script.is_public
     *
     * @mbg.generated
     */
    public String getIsPublic() {
        return isPublic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emergency_script.is_public
     *
     * @param isPublic the value for emergency_script.is_public
     *
     * @mbg.generated
     */
    public void setIsPublic(String isPublic) {
        this.isPublic = isPublic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emergency_script.script_type
     *
     * @return the value of emergency_script.script_type
     *
     * @mbg.generated
     */
    public String getScriptType() {
        return scriptType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emergency_script.script_type
     *
     * @param scriptType the value for emergency_script.script_type
     *
     * @mbg.generated
     */
    public void setScriptType(String scriptType) {
        this.scriptType = scriptType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emergency_script.submit_info
     *
     * @return the value of emergency_script.submit_info
     *
     * @mbg.generated
     */
    public String getSubmitInfo() {
        return submitInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emergency_script.submit_info
     *
     * @param submitInfo the value for emergency_script.submit_info
     *
     * @mbg.generated
     */
    public void setSubmitInfo(String submitInfo) {
        this.submitInfo = submitInfo == null ? null : submitInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emergency_script.have_password
     *
     * @return the value of emergency_script.have_password
     *
     * @mbg.generated
     */
    public String getHavePassword() {
        return havePassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emergency_script.have_password
     *
     * @param havePassword the value for emergency_script.have_password
     *
     * @mbg.generated
     */
    public void setHavePassword(String havePassword) {
        this.havePassword = havePassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emergency_script.password_mode
     *
     * @return the value of emergency_script.password_mode
     *
     * @mbg.generated
     */
    public String getPasswordMode() {
        return passwordMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emergency_script.password_mode
     *
     * @param passwordMode the value for emergency_script.password_mode
     *
     * @mbg.generated
     */
    public void setPasswordMode(String passwordMode) {
        this.passwordMode = passwordMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emergency_script.password
     *
     * @return the value of emergency_script.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emergency_script.password
     *
     * @param password the value for emergency_script.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emergency_script.server_user
     *
     * @return the value of emergency_script.server_user
     *
     * @mbg.generated
     */
    public String getServerUser() {
        return serverUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emergency_script.server_user
     *
     * @param serverUser the value for emergency_script.server_user
     *
     * @mbg.generated
     */
    public void setServerUser(String serverUser) {
        this.serverUser = serverUser == null ? null : serverUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emergency_script.server_ip
     *
     * @return the value of emergency_script.server_ip
     *
     * @mbg.generated
     */
    public String getServerIp() {
        return serverIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emergency_script.server_ip
     *
     * @param serverIp the value for emergency_script.server_ip
     *
     * @mbg.generated
     */
    public void setServerIp(String serverIp) {
        this.serverIp = serverIp == null ? null : serverIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emergency_script.script_user
     *
     * @return the value of emergency_script.script_user
     *
     * @mbg.generated
     */
    public String getScriptUser() {
        return scriptUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emergency_script.script_user
     *
     * @param scriptUser the value for emergency_script.script_user
     *
     * @mbg.generated
     */
    public void setScriptUser(String scriptUser) {
        this.scriptUser = scriptUser == null ? null : scriptUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emergency_script.update_time
     *
     * @return the value of emergency_script.update_time
     *
     * @mbg.generated
     */
    public Timestamp getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emergency_script.update_time
     *
     * @param updateTime the value for emergency_script.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emergency_script.param
     *
     * @return the value of emergency_script.param
     *
     * @mbg.generated
     */
    public String getParam() {
        return param;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emergency_script.param
     *
     * @param param the value for emergency_script.param
     *
     * @mbg.generated
     */
    public void setParam(String param) {
        this.param = param == null ? null : param.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emergency_script.script_status
     *
     * @return the value of emergency_script.script_status
     *
     * @mbg.generated
     */
    public String getScriptStatus() {
        return scriptStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emergency_script.script_status
     *
     * @param scriptStatus the value for emergency_script.script_status
     *
     * @mbg.generated
     */
    public void setScriptStatus(String scriptStatus) {
        this.scriptStatus = scriptStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emergency_script.content
     *
     * @return the value of emergency_script.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emergency_script.content
     *
     * @param content the value for emergency_script.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    private String type;

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }
}